### ISSUE TITLE
Blender 2.91

### ISSUE THREAD

**Issue by stinanickel** [hrbaer/Blender-ASCII-Grid-Import#3]
I tried to install the Script to the newest Blender 2.91 for Mac. Blender says that it was installed, but the Import Option doesn't show up in the import Menu. I hope it might not need so much change to adapt it to the new blender. Thanks for Your help. (I can do the transformation for the moment via Grasshopper/Rhino)

**Comment by LoicMICHEL5** [comment]
Hi,
I'm using Blender 2.91.2 on q PC and I have the same experience as stinanickel : upon installation, no   ESRI import apears in the import menu.  What do we miss ?
