### ISSUE TITLE
Plugin wont show up in list nor importer menu

### ISSUE THREAD

**Issue by PabloArjonilla** [hrbaer/Blender-ASCII-Grid-Import#4]
Hello hrbaer!

This is exactly what I need for a project I'm working on, but after a successful install **the option is not added to the importer**.

I tried using blender 2.80.0, as it was the lastest ported version, and also tried the 2.29 with no luck either. 

Do you have any idea about what could be the problem?

**Comment by hrbaer** [comment]
Hello Pablo

My current Blender version is 2.83 and the plugin installed and showed up correctly.
To track down the problem you encountered, please have a look at the following steps:

Install the zip-file, not the script alone
Check the Import ASCII box

The Blender preferences should look similar to the one below:

The ASCII Grid menu should then appear in the Import menu.




Hope this will help. I haven’t tested it with Blender version 3 so far.

Best regards
Hans Rudolf Baer

**Comment by PabloArjonilla** [comment]
Hello again.

Thank you for your help. The problem was I didn't install the whole ZIP.

¡Fantastic work!
