### ISSUE TITLE
Not working at Blender 3.2?

### ISSUE THREAD

**Issue by pabloserranobasterra** [hrbaer/Blender-ASCII-Grid-Import#5]
Hi! I was using your addon on previous Blender versions. I recently installed Blender 3.2 and now I get this message when trying to activate the addon:
AttributeError: 'module' object has no attribute 'INFO_MT_file_import'
Do I need anything to get it working?
Thanks!

**Comment by hrbaer** [comment]
Dear Pablo
Thank you for your report. I just updated the import add-on to Blender 3.2. It should now work as expected.
Best wishes
Hans Rudolf Baer

**Comment by pabloserranobasterra** [comment]
Thank you, Hans! Your addon is really useful for me to import to Blender geographic data exported from QGis as ASCII Grid. Thank you very much for the tool! Pablo Serrano Basterra - Virtualización Patrimonial  De: H. R. BaerEnviado: domingo, 19 de junio de 2022 11:06Para: hrbaer/Blender-ASCII-Grid-ImportCC: pabloserranobasterra; AuthorAsunto: Re: [hrbaer/Blender-ASCII-Grid-Import] Not working at Blender 3.2? (Issue #5) Dear PabloThank you for your report. I just updated the import add-on to Blender 3.2. It should now work as expected.Best wishesHans Rudolf Baer—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you authored the thread.Message ID: ***@***.***>
